services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: loja
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Adicione esta linha para definir a senha do usuário root
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d # Monta o diretório de scripts SQL
    ports:
      - "3306:3306"
    restart: always 
  app:
    image: jproxy:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/loja
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./target/jproxy.jar:/jproxy.jar
    command: ["java", "-jar", "/jproxy.jar"]
    ports:
      - "8080:8080"
    restart: always 
volumes:
  db_data:
